### ISSUE TITLE
Complete implementation of remaining Spark models

### ISSUE THREAD

**Issue by MLnick** [CODAIT/aardpfark#6]
## Classifiers 
- [ ] OneVsRest

## Regressors
- [ ] AFTSurvivalRegression
- [ ] IsotonicRegression

## Clustering
- [ ] BisectingKMeans
- [ ] GaussianMixture

## Other
- [ ] ALS

**Comment by Paxanator** [comment]
I have a working version of OneVsRest here: https://github.com/Paxanator/aardpfark/tree/models/onevsrest

But i think i'm making too many compromises going through it. Would appreciate some help figure out how to fit it into the existing structure

**Comment by laotang123** [comment]
> I have a working version of OneVsRest here: https://github.com/Paxanator/aardpfark/tree/models/onevsrest
> 
> But i think i'm making too many compromises going through it. Would appreciate some help figure out how to fit it into the existing structure

Thank you for your answer, except for the JSON PFA file. But something went wrong

Exception in thread "main" com.opendatagroup.hadrian.errors.PFASyntaxException: PFA syntax error at JSON line:col 134:38 (PFA field "fcns -> Stage_1_action -> do -> 0 -> let -> Stage_1_action_output -> do -> 0"): expecting expression, which may be ["string"], but no other array can be used as an expression
	at com.opendatagroup.hadrian.reader.jsonToAst$.readArgument(reader.scala:828)
	at com.opendatagroup.hadrian.reader.jsonToAst$.readExpression(reader.scala:744)
	at com.opendatagroup.hadrian.reader.jsonToAst$.readExpressionArray(reader.scala:659)
	at com.opendatagroup.hadrian.reader.jsonToAst$.readArgument(reader.scala:930)
	at com.opendatagroup.hadrian.reader.jsonToAst$.readExpression(reader.scala:744)
	at com.opendatagroup.hadrian.reader.jsonToAst$.readExpressionMap(reader.scala:678)
	at com.opendatagroup.hadrian.reader.jsonToAst$.readArgument(reader.scala:923)
	at com.opendatagroup.hadrian.reader.jsonToAst$.readExpression(reader.scala:744)
	at com.opendatagroup.hadrian.reader.jsonToAst$.readExpressionArray(reader.scala:659)
	at com.opendatagroup.hadrian.reader.jsonToAst$.readFcnDef(reader.scala:1144)
	at com.opendatagroup.hadrian.reader.jsonToAst$.readFcnDefMap(reader.scala:1114)
	at com.opendatagroup.hadrian.reader.jsonToAst$.readEngineConfig(reader.scala:298)
	at com.opendatagroup.hadrian.reader.jsonToAst$.parserToAst(reader.scala:160)
	at com.opendatagroup.hadrian.reader.jsonToAst$.apply(reader.scala:154)
	at com.opendatagroup.hadrian.jvmcompiler.PFAEngine$.fromJson(jvmcompiler.scala:2335)
	at com.ibm.aardpfark.PFATest01$.main(PFATest01.scala:43)
	at com.ibm.aardpfark.PFATest01.main(PFATest01.scala)
